name: Bug Report
description: Report Bug
title: "BUG: "
labels: [bug]
projects: 
  - "GithubProjectTemplate/7"
body:
  - type: input
    id: error-url
    attributes:
      label: SentryURL
      description: >
        SentryのURLを入力してください。
      placeholder: >
        https://sentry.io/alerts/rules/details/xxxxxx
    validations:
      required: true
