name: Add issue to project
 
on:
  issues:
    types:
      - opened
 
jobs:
  add_issue_to_project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - run: gh project item-add $PROJECT_ID --owner $PROJECT_OWNER --url $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.HAYTTY_PAT }}
          ISSUE: ${{ github.event.issue.html_url }}
          PROJECT_OWNER: haytty
          PROJECT_ID: 7
