name: Add issue to project
 
on:
  issues:
    types:
      - opened
 
jobs:
  add_issue_to_project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - run: gh project item-add $PROJECT_ID --owner $PROJECT_OWNER --url $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.HAYTTY_PAT }}
          ISSUE: ${{ github.event.issue.html_url }}
          PROJECT_OWNER: haytty
          PROJECT_ID: 7
  assign_yourself:
    name: Add author to issue
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit $ISSUE_NUMBER --add-assignee $CREATOR
        env:
          GITHUB_TOKEN: ${{ secrets.HAYTTY_PAT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          CREATOR: ${{ github.event.issue.user.login }}
